name: CI
on: push

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
      - name: run test
        run: |
          brew install gnu-time
          cargo build --release
          gtime cargo run --release -- 3
          gtime cargo run --release -- 1
